services:
  ai-rag-text-vector-vector-data-ingest:
    image: ai-rag-text-vector-vector-data-ingest:1.0
    build:
      context: .
      dockerfile: Dockerfile
      args:
         PROJECT_NAME: ai-rag-text-vector-vector-data-ingest
    volumes:
      - ../data:/app/data:rw
    environment:
      WATCH_DIR: /app/data/chunks/embeds
      ARCHIVE_DIR: /app/data/embeds/archive
      VECTOR_DB_HOST: chroma-vector-db
    networks:
      - ai-rag-text-vector-net
    container_name: ai-rag-text-vector-vector-data-ingest
    tty: true
    stdin_open: true

networks:
  ai-rag-text-vector-net:
    name: ai-rag-text-vector-net
