services:
  file-watcher:
    image: ${PROJECT_NAME}:${PROJECT_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
      args:
         PROJECT_NAME: ${PROJECT_NAME}
    volumes:
      - ../data:/app/data:rw
    environment:
      WATCH_DIR: ${DATA_HOME}/inbox
      ARCHIVE_DIR: ${DATA_HOME}/archive
      CHUNKS_DIR: ${DATA_HOME}/chunks
    container_name: "${PROJECT_NAME}" 
    tty: true
    stdin_open: true

